### ISSUE TITLE
Best way to refresh a component when the template string don't change?

### ISSUE THREAD

**Issue by archiloque** [WebReflection/uhtml#132] opened 2024-09-04 19:32 UTC
I have a question regarding the API: I have a specific need and can't figure how to make it work without using a hack and I wonder if I missed something or if I simply hit a uncommon use case.

I have a part of a page with several components, all generated from a single call to `render` with several holes.

I have specific rules to update some of fields of the displayed data in separated cases, but sometimes I want to update all the data at once.

Instead of writing a specific function for this case, I figured I could simply re-render the whole page part. The markup is the same but the data is changed.

Unfortunately, as far as I can understand it [here](https://github.com/WebReflection/uhtml/blob/478c9594279a6b1296dd57906b73bf79e696094c/esm/render/shared.js#L21) , as the markup don't change, my call to `render` does nothing because of the cache.

My current solution is to call `render(component, html``)` before calling the real `render`, this way the cache is dirtied and the real `render` works as expected (see [here](https://github.com/archiloque/tactical-fulcrum/blob/f224559dd549eb290e6d2768d8efdc459b5dc2bd/game/front/tower/info-bar/info-bar.ts#L105) ).

Is there a better approach ?

**Comment by WebReflection** [comment] 2024-09-05 14:38
I am not sure I am following ... could you provide a minimal reproducible example of your issue or where current logic fails? 'cause this line should already guarantee that if something changed on the DOM it will be reflected https://github.com/WebReflection/uhtml/blob/478c9594279a6b1296dd57906b73bf79e696094c/esm/render/shared.js#L20 ... the `hole.toDOM()` indeed updates all the things that changed but again, I am not really sure I am understanding your concerns ... if you have ownership of a node that should update itself and such node is part of a list of nodes already then it's up to you and the "*hack*" is not really a hack, rather the way to go as you don't want to bother the container if only a sub-part of it gets updated ... still, I need a use case to understand what you are after, I know my code already pretty well (and my logic too, it's how/where applied that I don't always know).

Thanks!

**Comment by archiloque** [comment] 2024-09-05 19:54
Ahh, with your explanations I had a fresh look at the code and I think I understand what I missed:

- I `render` some HTML for a part of a page
- I change the values of some sub-elements of this part's page, mostly with using `innerText`.
- I `render` again the initial HTML for the same part

My understanding is when I call the second `render`, the code is still caching the initial rendered value, because the code can't be aware of the changes I've made later.

Does it make sense to you?

**Comment by WebReflection** [comment] 2024-09-05 20:02
Not at all ... same nodes, smae thing on page ... if you manually change things in nodes without using *uhtml* you are on your own ... the **ownership** of the node matters, everything works by references and who does what ... why do you ever need to use manual `innerText` or `textContent` when you can just re-render everything every time you want?

The only issue people have with *uhtml* performance, to date, is that they think they can outsmart *uhtml* diffing by changing things on their own ... that's both asking for troubles and not about using *uhtml* ... in *uhtml* you render one or thousand times and call it a day, everything else is probably the reason you are here.

That being said, you have keyed VS non keyed references, if you use keyed, your issue doesn't exist but then again, until I see a reproducible issue or code that shows what is it that you are having issues with, I can't help, so I can close this too until further concrete examples I can reproduce.

**Closed by WebReflection** 2024-09-05 20:02 UTC
