### ISSUE TITLE
Custom Element MutationObserver

### ISSUE THREAD

**Issue by lemmon** [WebReflection/uhtml#31] opened 2020-12-03 17:10 UTC
I am not sure if this is related to uhtml or I am doing someting wrong. I am trying to attach a MutationObserver to a Custom Element with shadow DOM and watch for changes in the template (outside shadow DOM, not sure what the name is for this).

```html
html`
  <custom-element>${someValue}</custom-element>
`
```

I am looking to catch re-render event and apply content changes to my shadow DOM.

I am attaching [non-]working pen to illustrate my issue:
https://codepen.io/lemmonjuice/pen/rNMxxOw

When re-rendering the template nothing happens. However if I access the element directly and either change the textContent value or append a child the observer gets triggered. I was expecting that the re-render will trigger the observer as well. Checking the browser inspector I am seeing that the contetn was in fact updated properly.

Thanks.

**Comment by WebReflection** [comment] 2020-12-03 17:19
*uhtml* knows nothing about ShadowDOM, so it'll keep updating the element content, not its shadow-root, which is expected (or better, it's by design, no ShadowDOM checks whatsoever as ShadowDOM has mode closed that would make it fail anyway).

However, if you instrument your observe to move within its shadowRoot nodes, everything should be fine:

```js
      new MutationObserver((mutations) => {
        for (const {addedNodes} of mutations) {
          for (const node of addedNodes)
            this.shadowRoot.appendChild(node);
        }
      })
```

closing, as this is not something *uhtml* should solve, as it does exactly what it's expected to to 👋

**Closed by WebReflection** 2020-12-03 17:19 UTC

**Comment by lemmon** [comment] 2020-12-03 17:23
Nope. I understand that uhtml doesn't access Shadow DOM, that's not my intention. As per my example:

```html
html`
  <custom-element>${someValue}</custom-element>
`
```

...I am looking for changes of the `someValue` inside the `<custom-element>` tag. That element has Shadow DOM attached but changes happen within the main template whis uhtml has access to.

**Comment by WebReflection** [comment] 2020-12-03 17:40
I think my example code works as expected already, right?

**Comment by lemmon** [comment] 2020-12-03 17:54
Maybe my explanation is confusing. I am not seeing the MO gets triggered on re-render.

<img width="269" alt="a" src="https://user-images.githubusercontent.com/251591/101068048-8f469200-3598-11eb-8539-ab4297ed0947.png">

...after re-rendering the template serveral times I am seeing in the inspector that inner content of the element has changed, but...

<img width="528" alt="Screenshot 2020-12-03 at 18 49 53" src="https://user-images.githubusercontent.com/251591/101068198-b2714180-3598-11eb-8c18-a9a6d0cdee5a.png">

...the observer has been triggered only on first render. No other render triggers the thing. Only accessing the element via textContent or appendChild triggers the event.

**Comment by lemmon** [comment] 2020-12-03 17:56
When observing attributes I am getting the result I am expecting. But not with the inner content changes.

**Comment by lemmon** [comment] 2020-12-03 18:06
Okay, I guess I have figured it out. I need to pass combination of options:

```
{
  characterData: true,
  subtree: true,
}
```

Thank you!

**Comment by WebReflection** [comment] 2020-12-03 21:42
You need childList too
